-- Initial private schema for Toph. Generated by drizzle-kit from src/server/db/schema.ts and
-- reviewed by hand. The waveform_peaks_valid function below is hand-written: drizzle-kit does
-- not manage functions, and the work_logs check constraint depends on it, so it is created first.
CREATE SCHEMA "toph";
--> statement-breakpoint
-- Validates stored waveform peaks: a JSON array of at most 2,048 numbers, each between 0 and 1.
-- JSON numbers are always finite, so NaN/Infinity cannot be stored here.
CREATE FUNCTION "toph"."waveform_peaks_valid"(peaks jsonb) RETURNS boolean
LANGUAGE sql IMMUTABLE STRICT AS $$
  SELECT jsonb_typeof(peaks) = 'array'
     AND jsonb_array_length(peaks) <= 2048
     AND NOT EXISTS (
       SELECT 1 FROM jsonb_array_elements(peaks) AS element
       WHERE jsonb_typeof(element) <> 'number'
          OR (element::text)::numeric < 0
          OR (element::text)::numeric > 1
     );
$$;
--> statement-breakpoint
CREATE TABLE "toph"."dashboard_metric_snapshots" (
	"id" uuid PRIMARY KEY NOT NULL,
	"farm_id" uuid NOT NULL,
	"as_of_date" date NOT NULL,
	"recordings_today" integer NOT NULL,
	"new_recordings" integer NOT NULL,
	"active_workers" integer NOT NULL,
	"response_accuracy" numeric(5, 2),
	"source" text NOT NULL,
	"source_notes" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "dashboard_metric_snapshots_farm_id_as_of_date_unique" UNIQUE("farm_id","as_of_date"),
	CONSTRAINT "snapshots_counts_nonnegative" CHECK (recordings_today >= 0 AND new_recordings >= 0 AND active_workers >= 0),
	CONSTRAINT "snapshots_new_lte_recordings" CHECK (new_recordings <= recordings_today),
	CONSTRAINT "snapshots_accuracy_range" CHECK (response_accuracy IS NULL OR (response_accuracy >= 0 AND response_accuracy <= 100)),
	CONSTRAINT "snapshots_source_nonempty" CHECK (length(btrim(source)) > 0)
);
--> statement-breakpoint
CREATE TABLE "toph"."employees" (
	"id" uuid PRIMARY KEY NOT NULL,
	"farm_id" uuid NOT NULL,
	"display_name" text NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "employees_farm_id_id_unique" UNIQUE("farm_id","id"),
	CONSTRAINT "employees_display_name_nonempty" CHECK (length(btrim(display_name)) > 0)
);
--> statement-breakpoint
CREATE TABLE "toph"."farms" (
	"id" uuid PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"avatar_path" text,
	"timezone" text NOT NULL,
	"demo_reference_date" date NOT NULL,
	"is_demo" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "farms_name_nonempty" CHECK (length(btrim(name)) > 0),
	CONSTRAINT "farms_timezone_nonempty" CHECK (length(btrim(timezone)) > 0)
);
--> statement-breakpoint
CREATE TABLE "toph"."fields" (
	"id" uuid PRIMARY KEY NOT NULL,
	"farm_id" uuid NOT NULL,
	"name" text NOT NULL,
	"map_image_path" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "fields_farm_id_id_unique" UNIQUE("farm_id","id"),
	CONSTRAINT "fields_name_nonempty" CHECK (length(btrim(name)) > 0)
);
--> statement-breakpoint
CREATE TABLE "toph"."tags" (
	"id" uuid PRIMARY KEY NOT NULL,
	"farm_id" uuid NOT NULL,
	"label" text NOT NULL,
	"normalized_label" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "tags_farm_id_id_unique" UNIQUE("farm_id","id"),
	CONSTRAINT "tags_farm_id_normalized_label_unique" UNIQUE("farm_id","normalized_label"),
	CONSTRAINT "tags_label_nonempty" CHECK (length(btrim(label)) > 0),
	CONSTRAINT "tags_label_trimmed" CHECK (label = btrim(label)),
	CONSTRAINT "tags_label_max_length" CHECK (length(label) <= 40),
	CONSTRAINT "tags_normalized_label_nonempty" CHECK (length(normalized_label) > 0)
);
--> statement-breakpoint
CREATE TABLE "toph"."work_log_tags" (
	"farm_id" uuid NOT NULL,
	"work_log_id" uuid NOT NULL,
	"tag_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "work_log_tags_pk" PRIMARY KEY("work_log_id","tag_id")
);
--> statement-breakpoint
CREATE TABLE "toph"."work_logs" (
	"id" uuid PRIMARY KEY NOT NULL,
	"farm_id" uuid NOT NULL,
	"employee_id" uuid NOT NULL,
	"field_id" uuid NOT NULL,
	"activity" text NOT NULL,
	"work_date" date NOT NULL,
	"start_at" timestamp with time zone NOT NULL,
	"end_at" timestamp with time zone NOT NULL,
	"summary" text NOT NULL,
	"transcript" text,
	"is_new" boolean DEFAULT false NOT NULL,
	"recording_path" text,
	"recording_duration_seconds" double precision,
	"recording_is_demo" boolean DEFAULT false NOT NULL,
	"waveform_asset_path" text,
	"waveform_peaks" jsonb,
	"waveform_source" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "work_logs_farm_id_id_unique" UNIQUE("farm_id","id"),
	CONSTRAINT "work_logs_activity_nonempty" CHECK (length(btrim(activity)) > 0),
	CONSTRAINT "work_logs_end_after_start" CHECK (end_at > start_at),
	CONSTRAINT "work_logs_recording_duration_valid" CHECK (recording_duration_seconds IS NULL OR (recording_path IS NOT NULL AND recording_duration_seconds > 0 AND recording_duration_seconds < 'Infinity'::double precision)),
	CONSTRAINT "work_logs_waveform_source_valid" CHECK (waveform_source IS NULL OR waveform_source IN ('design_reference', 'audio')),
	CONSTRAINT "work_logs_waveform_peaks_valid" CHECK (waveform_peaks IS NULL OR toph.waveform_peaks_valid(waveform_peaks))
);
--> statement-breakpoint
ALTER TABLE "toph"."dashboard_metric_snapshots" ADD CONSTRAINT "dashboard_metric_snapshots_farm_id_farms_id_fk" FOREIGN KEY ("farm_id") REFERENCES "toph"."farms"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "toph"."employees" ADD CONSTRAINT "employees_farm_id_farms_id_fk" FOREIGN KEY ("farm_id") REFERENCES "toph"."farms"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "toph"."fields" ADD CONSTRAINT "fields_farm_id_farms_id_fk" FOREIGN KEY ("farm_id") REFERENCES "toph"."farms"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "toph"."tags" ADD CONSTRAINT "tags_farm_id_farms_id_fk" FOREIGN KEY ("farm_id") REFERENCES "toph"."farms"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "toph"."work_log_tags" ADD CONSTRAINT "work_log_tags_farm_id_farms_id_fk" FOREIGN KEY ("farm_id") REFERENCES "toph"."farms"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "toph"."work_log_tags" ADD CONSTRAINT "work_log_tags_work_log_fk" FOREIGN KEY ("farm_id","work_log_id") REFERENCES "toph"."work_logs"("farm_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "toph"."work_log_tags" ADD CONSTRAINT "work_log_tags_tag_fk" FOREIGN KEY ("farm_id","tag_id") REFERENCES "toph"."tags"("farm_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "toph"."work_logs" ADD CONSTRAINT "work_logs_farm_id_farms_id_fk" FOREIGN KEY ("farm_id") REFERENCES "toph"."farms"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "toph"."work_logs" ADD CONSTRAINT "work_logs_employee_fk" FOREIGN KEY ("farm_id","employee_id") REFERENCES "toph"."employees"("farm_id","id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "toph"."work_logs" ADD CONSTRAINT "work_logs_field_fk" FOREIGN KEY ("farm_id","field_id") REFERENCES "toph"."fields"("farm_id","id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "work_log_tags_farm_tag_log_idx" ON "toph"."work_log_tags" USING btree ("farm_id","tag_id","work_log_id");--> statement-breakpoint
CREATE INDEX "work_logs_farm_date_idx" ON "toph"."work_logs" USING btree ("farm_id","work_date","id");--> statement-breakpoint
CREATE INDEX "work_logs_farm_employee_idx" ON "toph"."work_logs" USING btree ("farm_id","employee_id");--> statement-breakpoint
CREATE INDEX "work_logs_farm_field_idx" ON "toph"."work_logs" USING btree ("farm_id","field_id");--> statement-breakpoint
CREATE INDEX "work_logs_farm_activity_idx" ON "toph"."work_logs" USING btree ("farm_id","activity");--> statement-breakpoint
CREATE VIEW "toph"."dashboard_logs" AS (select
  l.id,
  l.farm_id,
  l.employee_id,
  e.display_name as employee_name,
  l.activity,
  l.work_date,
  l.field_id,
  f.name as field_name,
  f.map_image_path as field_map_image_path,
  l.start_at,
  l.end_at,
  l.summary,
  l.is_new,
  l.recording_path,
  l.recording_duration_seconds,
  l.recording_is_demo,
  l.waveform_asset_path,
  l.waveform_peaks,
  l.waveform_source,
  (
    select coalesce(jsonb_agg(jsonb_build_object('id', t.id, 'label', t.label) order by t.normalized_label, t.id), '[]'::jsonb)
    from toph.work_log_tags wt
    join toph.tags t on t.id = wt.tag_id and t.farm_id = wt.farm_id
    where wt.work_log_id = l.id
  ) as tags,
  l.created_at,
  l.updated_at
from toph.work_logs l
join toph.employees e on e.id = l.employee_id and e.farm_id = l.farm_id
join toph.fields f on f.id = l.field_id and f.farm_id = l.farm_id);