export type Employee = { id: string; name: string; role: string; email: string; phone: string; status: "Active" | "Inactive"; joinedAt: string };
export type ScheduleItem = { id: string; title: string; employeeId: string; fieldId: string; date: string; startTime: string; endTime: string; notes: string; status: "Scheduled" | "Completed" };
export type Review = { logId: string; status: "Pending" | "Approved" | "Flagged"; note: string; updatedAt: string };
export type SavedReport = { id: string; name: string; kind: "activity" | "compliance" | "hours"; from: string; to: string; createdAt: string };
export type Message = { id: string; employeeId: string; body: string; from: "admin" | "employee"; createdAt: string; read: boolean };
export type SupportTicket = { id: string; subject: string; category: "General" | "Technical" | "Account"; body: string; status: "Open" | "Closed"; createdAt: string };
export type WorkspaceSettings = { farmName: string; contactName: string; email: string; timezone: string; notifications: { recordings: boolean; weekly: boolean; reminders: boolean } };
export type WorkspaceState = { employees: Employee[]; schedule: ScheduleItem[]; reviews: Review[]; reports: SavedReport[]; messages: Message[]; tickets: SupportTicket[]; settings: WorkspaceSettings };
export type WorkspaceResponse = { data: WorkspaceState; revision: number };
